[package]
name = "wasm-test"
version = "0.1.0"
authors = ["mattrossman <rossman@gatech.edu>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.74"
